Mingi drone circle
j55blanchet/fleet-command-multirobotsystems-cs269 pull request #16
Opened 2021-05-30 02:28 UTC by MingiJeong

**<What I've done>**
**1. new README**
- test bed based on robot configurations for the sake of robust algorithm tests

**2. SurroundingBehaviorDriver**
- vortex-based model. See my attached note on the slack for mathematical derivation if you are curious
- Maintain similar distance when they are circling
- All motion parameters are implemented with service samely as flocking. Note that params of the behavior is different from ones in flocking. Yes, they should be.

**3. BaseBehaviorDriver**
- class as parent of surrounding and flocking.
- inheritance
- avoid repetition and more modular code

**4. Aux**
- Helper functions went to aux functions

**5. Misc.**
- To make code modular and easy to debug

**<Suggestion and check point to my and other’s code I’ve seen>**
**1. Enemy**
- Too fast? Drones rarely catch up.
- Too close to the shore? We can assume more like they don’t want to get grounded, so that drones can detain by circling (can go between shore and drone).

**2. Guard and detainment**
- As I shared the video, the same code can behave as guard (flagship) vs detainment (enemy)
- I made property and function in SurroundingBehavior.py with Enum. I saw Julien did something in Drone.py. So, in connection with that, I believe we can make Service that trigger a switch between guard and detainment. (line 120, 121 in SurroundingDriver.py)

**3. Surrounding base_psn**
- currently I have this property for the main base position of vortex. We can connect Julien’s point implementation in Drone.py.

**4. In consideration of multiple enemies**
- I marked with “TODO” in flagship.py, flockingdriver.py, surroundingdriver.py

**5. obstacle avoidance in BaseBehaviorDriver**
- I copied original flocking laser callback into here. I noticed that obstacle avoidance coefficient is not used and “distance” is used instead.
- Also, obstacle avoidance force is not normalized, thus making threshold hard to adjust (0.03). I believe normalization as other forces enable us to handle the coefficients easily

**<Test>**
 Please see the videos.
[](https://drive.google.com/drive/folders/1B2m6RKBH_wDaIKCXSwl8gST7Mk80pSGV?usp=sharing)
For the following enemy cases:
**1. hold_psn:**
- when “capture enemy” begins, flocking of some robots are stuck → parameter

**2. evade, wander:**
- As I mentioned above,  the enemy is too fast (in order to detain, they should be slower than the friendly drones)
- the enemy is too close to the shore. Therefore, Our drones cannot go inside.
- flocking sometimes make robots stuck in the wall 

**<From now on>**
All can be rigorously tested with param tuning (flocking, surrounding) + minor adjust, implementation (e.g., service for switching mode of surrounding, connection with the current set up like surrouding point, etc )
- I also believe that some params should be adaptive. For example, vortex radius for flagship must be larger than for enemy in consideration of flagship length. → this can be one of the factors that make drones can go between shore and enemy.

2021-05-30 13:45 UTC, JosephGatto approved these changes

2021-05-30 17:44 UTC, j55blanchet requested changes

2021-05-30 17:44 UTC, j55blanchet commented on CMakeLists.txt
> +   SetSurroundMotionParameters.srv
`SetSurroundParameters` was really just a placeholder for whatever you needed here. You can consolidate `SetSurroundParameters` and `SetSurroudnMotionParameters` into a single service

2021-05-30 17:44 UTC, j55blanchet commented on launch/fleet_command_base.launch
> +        <arg name="behavior" value="wander" />
i didn't do this yet, but would be good to have this as an arg to this launch file so that we can specify enemy behavior via the command line (with `enemy_behavior:=wander`, for example).

2021-05-30 17:44 UTC, j55blanchet commented on src/fleet_command/components/FlockingDriver.py
> +            - 2 step: flocking force including alignment, cohesion, separation
add to step 2 comment: targeting

2021-05-30 17:44 UTC, j55blanchet commented on src/fleet_command/components/FlockingDriver.py
> +    to make robots perform flocking behavior, e.g., go to a point
might be good to explain in file comment here that this is an extension of what is typically considered flocking behavior.

Typical flocking is alignment + cohesion + separation.
This code extends typical flocking by adding obstacle avoidance and point-targeting

2021-05-30 17:44 UTC, j55blanchet commented on src/fleet_command/components/BaseBehaviorDriver.py
> +        cmd_msg.linear.x = self.max_linear_velocity * percent_directly_ahead
comment is a bit inaccurate - it's not a fixed linear velocity. The linear velocity scales inversely with the angular velocity.

2021-05-30 17:44 UTC, j55blanchet commented on src/fleet_command/components/BaseBehaviorDriver.py
> +class BaseBehaviorDriver():
Nice work refactoring this to have the common base class :D

2021-05-30 17:44 UTC, j55blanchet commented on src/fleet_command/components/FlockingDriver.py
>          net_force += self.obstacle_avoidance_force * self.obstacle_avoidance_distance
it definitely should be obstacle_avoidance_coefficient! Plz make the change. May need to increase the value of that coefficient as well.

2021-05-30 17:44 UTC, j55blanchet commented on src/fleet_command/components/FlockingDriver.py
> +        # If so, all applies to surrounding, too
I don't want to normalize the obstacle_avoidance_force, because in this case the magnitude is quite important. If we are further away from obstacles, the force should be smaller, and if we are near them, the force should be much bigger. Normalizing the obstacle avoidance force would remove that "force magnitude" information.'

Put another way, the reason we want to don't normalize the obstacle avoidance force whereas we do normalize the other flocking forces is because we want the obstacle avoidance force to only activate when it's relevant in the simulation, whereas we always want the flocking forces to be active.

Thinking about it now, it may actually make sense to stop normalizing or change how we normalize the other flocking forces. (because, for example, we want the relative influence of separation to be dependent on the how close the nearby ships are). But we can look into that another time.

2021-05-30 17:44 UTC, j55blanchet commented on src/fleet_command/components/BaseBehaviorDriver.py
> +        force_angle = math.atan2(net_force[1], net_force[0])
If the net_force is (0, 0) , `atan2` will throw an exception. Suggest adding a base case that simply returns the default twist msg if the net_force magnitude is zero.

2021-05-30 17:44 UTC, j55blanchet commented on src/fleet_command/components/SurroundingDriver.py
> +        self.master_flagship = master_flagship
this variable is already present in the `BaseBehaviorDriver`, right?

2021-05-30 17:44 UTC, j55blanchet commented on src/fleet_command/components/SurroundingDriver.py
> +class SurroundingObject(Enum):
I suggest simply accepting the surround target via the `SetSurroundMotionParametersRequest`. That way, this code can be flexible for surrounding flagship, enemy, or an arbitrary point even in the multi-flagship, multi-enemy scenario

2021-05-30 17:44 UTC, j55blanchet commented on src/fleet_command/components/SurroundingDriver.py
> +    def surround_enemy(self):
see above comment in reference to just accepting the `base_position` directly

2021-05-30 17:44 UTC, j55blanchet commented on src/fleet_command/components/SurroundingDriver.py
> +        # vortex equation base
can you provide a link in the comments somewhere to documentation on how these equations are derived? Like a blog post or something for reference?

2021-05-30 17:44 UTC, j55blanchet commented on src/fleet_command/components/SurroundingDriver.py
> +        self.surrounding_base_psn = None  # type: 1 x 2 numpy array
suggest renaming this to `surround_target` or `surround_center_point`

2021-05-30 17:44 UTC, j55blanchet commented on src/fleet_command/components/SurroundingDriver.py
> +        self.target_point = None # TODO this should be resolved by self.surrounding_base_psn
I don't see `target_point` being used anywhere - delete it?

2021-05-30 17:44 UTC, j55blanchet commented on src/fleet_command/components/aux_function.py
> +class Vector:
can we just use numpy arrays / functions instead?

2021-05-30 17:44 UTC, j55blanchet commented on src/fleet_command/Flagship.py
>  Flagship class definition
`set_surround_params` and the associated functionality was intended to be a placeholder for you. Currently, it doesn't do anything of value, but you could use it to update the surround_target for the Drones in a flexible way.

2021-05-31 23:46 UTC, j55blanchet approved these changes

2021-05-31 23:46 UTC, j55blanchet commented on launch/fleet_command.launch
> +    <arg name="behavior" default="hold_position" />
nit: rename to `enemy_behavior`. Currently, it's not clear what behavior is referring to (for example, could be drone behavior, which would be confusing).

2021-05-31 23:46 UTC, j55blanchet commented on launch/fleet_command_base.launch
> +    <arg name="behavior" default="" /> <!-- enemy -->
same comment as other file - rename to enemy_behavior. (there's no need to rename the arg in `enemy.launch`, however, as it's clear by file context that behavior refers to the enemy.

2021-05-31 23:46 UTC, j55blanchet commented on launch/fleet_command_text.launch
> +    <arg name="behavior" default="hold_position" />
see other comments in regards to behavior name - when it's not clear which ship the behavior would refer to, rename it to `enemy_behavior`

2021-05-31 23:46 UTC, j55blanchet commented on src/fleet_command/Flagship.py
> +            other_nearby_drones.remove(closeby_drone) # cxclude itself
nit: comment typo. "exclude"

2021-05-31 23:46 UTC, j55blanchet commented on src/fleet_command/Flagship.py
> +        # TODO: we can consolidate as general surrounding by if condition flagship or enemy
agreed, there's probably a way to reduce code duplication. But can address in future PR

2021-05-31 23:46 UTC, j55blanchet commented on src/fleet_command/components/FlockingDriver.py
> +DEFAULT_OBSTACLE_AVOID_COEFFICIENT = 12 # matching it with distance from the current calibration
i don't understand your comment here. why do we want the coefficient to be the same value as the distance?

2021-05-31 23:46 UTC, j55blanchet commented on src/fleet_command/components/FlockingDriver.py
> +        robot_name,
nit: indent lines 81-86

2021-05-31 23:53 UTC, merged