Added evaluator node and corresponding visualization
j55blanchet/fleet-command-multirobotsystems-cs269 pull request #18
Opened 2021-06-03 17:45 UTC by JosephGatto

The evaluator node checks the following 4 conditions 

1. Check if the enemy is inside of the convex hull produced by the set of vertices corresponding to the drones and (when applicable) shore locations. 
- Note: Shore locations are all points under 15m from the enemy. The final set of shore points used in the convex hull are a subset of 4 shore points chosen using a farthest neighbor algorithm so we get good spacing around the enemy and don't over-complicate our point set. 
2. Ensure distance between enemy and all friendly ships is less than delta 
3. Ensure friendly ships are no less than 2.5*epsilon away from each other. 
4. Check that each friendly ship is less than delta away from the shore. This is done by using the mean shore point from the final set of shore points as a reference. 

To visualize the evaluation, every few seconds a matplotlib figure is saved displaying the drone (+ shore) set, the enemy, and the current convex hull. When ROS shuts down, a video is generated from all plots to visualize the detainment process. Note that I have updated the README to include the ffmpeg dependency. 

So far the experiments I have run work well. However, our current code seems to struggle with the enemy along the shore line so I was not able to fully test that scenario.

2021-06-03 19:19 UTC, j55blanchet requested changes

2021-06-03 19:19 UTC, j55blanchet commented on src/fleet_command/Evaluator.py
> +        x_img_index, y_img_index = list(range(320)), list(range(180))
nit: can we define these numbers as constants at the top of the file?

2021-06-03 19:19 UTC, j55blanchet commented on src/fleet_command/Evaluator.py
> +    def condition_1(self, friendly_locations, shore_points, enemy):
can you rename the conditions methods to describe what they actually are testing? I know you describe this in the comments, but then readers are forced to locate the method definition to figure out what's going on.

Things like:
* `convexhull_surrounds_enemy()`
* `friendlyships_within_detainment_distance()`
* `capture_radius_is_enforced()`

2021-06-03 19:19 UTC, j55blanchet commented on src/fleet_command/Evaluator.py
> +        # Check if friendly drone farthest from the enemy is less than the min detainment distance delta
nit: comment should say "... less than the _max_ detainment distance"

2021-06-03 19:19 UTC, j55blanchet commented on src/fleet_command/Evaluator.py
> +        Condition 3: Make sure the drones are no less than 2.5*epsilon away from each other. This ensures a tight formation around the enemy.
this condition as implemented is stricter than in our problem statement. We really just need the distance between ships _along the perimeter_ of the convex hull to be less than 2x the capture distance. We don't need to check the distances between pairs of drones that aren't next to each other along the perimeter.

2021-06-03 19:19 UTC, j55blanchet commented on src/fleet_command/Evaluator.py
> +        Condition 3: Make sure the drones are no less than 2.5*epsilon away from each other. This ensures a tight formation around the enemy.
I recommend constructing a convex hull (with shore points) like in the previous condition and then just comparing each ship with the next one (as well as last one in the list with the first one). 

Note that the maximum allowed length of the edge depends on whether the points are ships or shore points:
* edge between two ships: max distance = 2 * capture distance
* edge between one ship and the shore: max_distance = capture_distance
* edge between two shore points: max_distance = math.inf (no enforced max distance)

2021-06-03 19:19 UTC, j55blanchet commented on src/fleet_command/Evaluator.py
> +        Condition 4: Ensure that the distance between a single representitve shore point and the friendly drones is less than delta.
see above: I recommend eliminating this condition and merging the shore check into a perimeter-convex-hull check as described in the above comment.

2021-06-03 19:19 UTC, j55blanchet commented on src/fleet_command/Evaluator.py
> +        Returns eucledian distance between 2 points
nit: we already have distance functions in `aux_functions`; no need to repeat ourselves.

2021-06-03 19:21 UTC, JosephGatto commented on nodes/evaluator
> +    while not rospy.is_shutdown():
good catch, I had meant to remove this.

2021-06-03 21:10 UTC, j55blanchet approved these changes
Just a couple nits, but looks good!

2021-06-03 21:10 UTC, j55blanchet commented on launch/evaluator.launch
> +            <param name="robot_total" value="$(arg robot_total)" />
nit: can remove `robot_total`, as it isn't needed anymore

2021-06-03 21:10 UTC, j55blanchet commented on launch/fleet_command_base.launch
> +        <arg name="robot_total" value="5" />
nit: robot_total isn't needed here either

2021-06-03 21:10 UTC, j55blanchet commented on src/fleet_command/Evaluator.py
> +        print(friendly_ships)
nit: use rospy.logXXX intead of print

2021-06-03 21:10 UTC, j55blanchet commented on src/fleet_command/Evaluator.py
> +        Condition 3: Make sure the drones are no less than 2.5*capture_distance away from each other. This ensures a tight formation around the enemy.
nit: update comment to reflect altered functionality

2021-06-03 21:10 UTC, j55blanchet commented on src/fleet_command/Evaluator.py
> +        return True
nit: can remove the rest of the function; the logic will return here

2021-06-03 22:17 UTC, MingiJeong approved these changes

2021-06-04 15:57 UTC, j55blanchet approved these changes

2021-06-04 15:57 UTC, j55blanchet commented on launch/evaluator.launch
> +    <arg name="robot_total" default="" />
nit: you don't need robot total here either.

2021-06-04 15:57 UTC, j55blanchet commented on src/fleet_command/Evaluator.py
> +        return True if max_d < self.detainment_radius else False
nit: this ternary operator is unnecessary. Can directly do `return max_d < self.detainment_radius`

2021-06-04 15:57 UTC, j55blanchet commented on src/fleet_command/Evaluator.py
> +                            if self.map[i,j] > 50:
nit: replace hardcoded 50 with a constant defined at top of file

2021-06-04 15:57 UTC, j55blanchet commented on src/fleet_command/Evaluator.py
> +            if sum(detained_conditions) == NUM_CONDITIONS:
nit: rather than having the hardcoded `NUM_CONDITIONS` value, why not just check to ensure all the values in the detained conditions array are true directly using pythons native `all()` method? 

Could be:

```
if all(detained_conditions):
   # rest of logic
```

2021-06-05 16:54 UTC, merged