Mingi
j55blanchet/fleet-command-multirobotsystems-cs269 pull request #3
Opened 2021-05-17 16:50 UTC by MingiJeong

here merge request
Main thing
1) AIS message
2) CMakeList and package.xml as per Alberto's structure suggestion
3) node and class definition (super class) with much more modular.

2021-05-17 17:29 UTC, j55blanchet requested changes
Great work! Left a few suggestions. You'll need to merge from master in order to get the latest changes.

2021-05-17 17:29 UTC, j55blanchet commented on nodes/odometry_transform_publisher
> +    Purpose : Make a separate frame denoting the robot's ground truth pose frame
I deleted this file, as we do not need to use the ground truth pose (we can simply use robot_x/base_link, as it will be accurate due to gps localization).

2021-05-17 17:29 UTC, j55blanchet commented on nodes/static_transform_publisher
> +    All robot_x/odom is based on origin (0, 0); thus arg for x,y,z, rotation all 0
nit: clarify that this this is only true for Stage. In the general case, odom wouldn't necessarily be based off of world origin frame.

2021-05-17 17:29 UTC, j55blanchet commented on msg/AIS_message.msg
> +std_msgs/Header header
We should discuss how AIS will be used in our simulation. I feel like the functionality of AIS as far as Pose overlaps with the tf2 hierarchy (i.e., to determine where a robot is we'd likely just look up it's frame in the transform listener).

However, AIS can help us with:

- Getting the list of all other ships, including which team they're on
    - **Suggestion**: add an 'affiliation' field to AIS so ship AI can know which are friendly / unfriendly? 
- Determining how big those other ships are
- Getting the velocity & heading of other ships

2021-05-17 17:29 UTC, j55blanchet commented on package.xml
> -  <!-- <author email="jane.doe@example.com">Jane Doe</author> -->
Nit: can we add author tags for us?

2021-05-17 17:29 UTC, j55blanchet commented on src/fleet_command/Drone.py
> +    def spin(self, rate):
I think it might be better to put the `spin` message in the super class, so that we don't need to repeat the AIS message publishing logic.

Then, make the superclass an abstract base class and add an abstract method in the superclass called `update` that subclasses would be required to override. The update method would be called once per spin cycle. 

[Here](https://stackoverflow.com/questions/13646245/is-it-possible-to-make-abstract-classes-in-python) is a link on how to make a class be an abstract class.

2021-05-17 17:29 UTC, j55blanchet commented on src/fleet_command/Super.py
> +Super class for all common object
Can we rename this to `Ship` or `ShipBase`? Just calling it `Super.py` isn't descriptive, because it could be a superclass for any other python class. Calling it Ship or ShipBase makes the intended functionality more clear.

2021-05-17 17:29 UTC, j55blanchet commented on src/fleet_command/aux_function.py
> +def heading_transform_clockwise(orientation_in_pose_msg):
I like having this file to house misc functions.

Can we rename this function to better describe what it does (i.e., make it a verb?) Perhaps something like:

- `get_yaw_from_pose` or
- `get_yaw_from_quaternion`

Also, can we return the angle in radians?

2021-05-17 17:29 UTC, j55blanchet commented on src/fleet_command/aux_function.py
> +    # [000, 270) 1st ~ 3rd quadrant
I think the logic for these two if statements could be simplified:

    # normalize yaw to [-math.pi, math.pi)
    return (yaw + 2 *math.pi) % (2 * math.pi) - math.pi

2021-05-17 17:29 UTC, j55blanchet commented on worlds/drone.inc
> +    # TODO range max limit
I've updated this file in master. In the future I'll submit pull requests as well. But you'll need to merge from master to get my latest changes.

2021-05-17 20:21 UTC, MingiJeong commented on nodes/odometry_transform_publisher
> +    Purpose : Make a separate frame denoting the robot's ground truth pose frame
"You'll need to merge from master in order to get the latest changes."
Sorry as you know, I am a bit newbie on github collaboration as a team. 
If I understand correctly, you mean "master" -> "mingi" merge first to apply the new change.
Then, I submit "mingi" -> "master" merge request again to make you apply my change, correct?

apology in advance if I miss one of the next times :)

2021-05-17 20:22 UTC, MingiJeong commented on nodes/odometry_transform_publisher
> +    Purpose : Make a separate frame denoting the robot's ground truth pose frame
for this node, indeed. I was wondering why we needed. you got the correct direction

2021-05-17 20:23 UTC, MingiJeong commented on nodes/static_transform_publisher
> +    All robot_x/odom is based on origin (0, 0); thus arg for x,y,z, rotation all 0
yeah that's why I made a comment here. It was a bit off from my common sense of odom. It is based on Stage

2021-05-17 20:25 UTC, MingiJeong commented on msg/AIS_message.msg
> +std_msgs/Header header
yeah all valid points. I also think that in the real robot scenario, we don't directly access the other robot's pose thru the TF tree, I thought the access via AIS makes more sense? like God already knows, but robot in the scene doesn't know? (similar to PA3 questions you asked me, if I remember correctly).

2021-05-17 20:25 UTC, MingiJeong commented on package.xml
> -  <!-- <author email="jane.doe@example.com">Jane Doe</author> -->
yeah we should. plus MIT license. I will. I put this as less priority for yesterday as being lazy :)

2021-05-17 20:37 UTC, MingiJeong commented on src/fleet_command/Drone.py
> +    def spin(self, rate):
Indeed. I did just for a quick test this morning. The main reason I did use inheritance was to avoid repetition. For this reason, I was about to make that spin as a common one, too. I think there are two components in the spin: (1) common spin properties included in Super class (2) individual spin properties in Descendant class (enemy, drone, flagship)

2021-05-17 20:37 UTC, MingiJeong commented on src/fleet_command/Super.py
> +Super class for all common object
yeah

2021-05-17 20:38 UTC, MingiJeong commented on src/fleet_command/aux_function.py
> +def heading_transform_clockwise(orientation_in_pose_msg):
yeah I will. 
It is also possible. I just followed the normal marine industry, maybe I can also pass the flag whether we can return in radians or angles.

2021-05-17 20:38 UTC, MingiJeong commented on src/fleet_command/aux_function.py
> +    # [000, 270) 1st ~ 3rd quadrant
Let me recheck for this

2021-05-17 20:39 UTC, MingiJeong commented on worlds/drone.inc
> +    # TODO range max limit
I will ask this

2021-05-17 21:56 UTC, j55blanchet commented on nodes/static_transform_publisher
> +    All robot_x/odom is based on origin (0, 0); thus arg for x,y,z, rotation all 0
Makes sense. Just add "In stage, all robot_x/odom is...." and we're good

2021-05-17 21:58 UTC, j55blanchet commented on msg/AIS_message.msg
> +std_msgs/Header header
True. I'm cool with using AIS instead of tf2 for position as well.

Up to you if youd rather make affiliation part of the ship name ("<affiliation>/<shipname") or a separate field

2021-05-18 01:12 UTC, MingiJeong commented on src/fleet_command/aux_function.py
> +    # [000, 270) 1st ~ 3rd quadrant
I think it does not give that way. e.g., if yaw = -math.pi/2 (counter clock wise 90 degree), dividing part quotient will be "0", which result in -math.pi overall. So, the intended output as 0 is different from "-math.pi". We can revisit this later, but not that important for now :) Anyhow I am returning in radians correctly.

2021-05-18 13:23 UTC, j55blanchet approved these changes

2021-05-18 13:23 UTC, j55blanchet commented on src/fleet_command/Ship.py
> +    def move_base(self, destination):
This works for now. I was thinking we might actually use the [ROS move_base package](https://wiki.ros.org/move_base) to implement ship movement, that way it can do local/global planning and avoid obstacles. We can add that later

2021-05-18 13:23 UTC, j55blanchet commented on src/fleet_command/Ship.py
> +            while not rospy.is_shutdown():
I think we'll want to write this a different way - as written, it will take over from the main control loop. We can look at this after the merge

2021-05-18 13:23 UTC, j55blanchet commented on src/fleet_command/Ship.py
> +DEFAULT_INFORMATION_TOPIC = 'ais_info'
Should we make the AIS topic an absolute namespace `/ais_info`, that way all AIS messages get sent to the same topic? It provides ships a way of easily detecting the positions of all other ships, rather than having to subscribe to multiple AIS nodes

2021-05-18 13:24 UTC, j55blanchet commented on src/fleet_command/Drone.py
> +    def spin(self, rate):
Let's postpone talking about the way we do spin until this is merged.

2021-05-18 13:37 UTC, MingiJeong commented on src/fleet_command/Ship.py
> +    def move_base(self, destination):
ohh I see. In such a case, it must be somehow related to using occupancy grid

2021-05-18 13:40 UTC, MingiJeong commented on src/fleet_command/Ship.py
> +DEFAULT_INFORMATION_TOPIC = 'ais_info'
so, the idea will be all ships publishing via /ais_info not via /robot_i/aisinfo, such that one subscriber handles it from another robot? I guess then you wanna deal with robot name and id in the message from who published, right despite one subscriber?

2021-05-18 13:40 UTC, merged